#!/bin/bash

# Stop applying color
Color_Off="\033[0m"

###-Regular-###
Color_Red="\033[0;31m"
Color_Green="\033[0;32m"
Color_Yellow="\033[0;33m"
Color_Blue="\033[0;34m"
Color_Purple="\033[0;35m"
Color_Cyan="\033[0;36m"
Color_White="\033[0;37m"

####-Bold-####
Color_Bold_Red="\033[1;31m"
Color_Bold_Green="\033[1;"
Color_Bold_Yellow="\033[1;33m"
Color_Bold_Blue="\033[1;34m"
Color_Bold_Purple="\033[1;35m"

###-Intensive-###
Color_Intense_Red="\033[0;91m"
Color_Intense_Green="\033[0;92m"
Color_Intense_Yellow="\033[0;93m"
Color_Intense_Blue="\033[0;94m" 
Color_Intense_Purple="\033[0;95m"
Color_Intense_Cyan="\033[0;96m" 
Color_Intense_White="\033[0;97m"
##################
