#!/bin/bash

command -v convert >/dev/null 2>&1 || { echo "ERROR: Please install ImageMagic"; exit 1; }
[ -z $1 ] && { echo "ERROR: Please specify gallery folder name."; exit 1; }
[ -d "$1" ] || { echo "ERROR: Gallery directory $1 NOT FOUND. Can't continue."; exit 1; }

[ -d "./img" ] || { echo "WARNING: Missing the ./img folder. Is this the right directory?"; exit 1; }
[ -d "./_posts" ] || { echo "WARNING: Missing ./_post folder. Run from the root of your Jekyll site."; }

DIR="$1"
FILES=`ls $DIR/*.???`

[ -d "$DIR/thumb" ] || { mkdir $DIR/thumb; }

echo '<div class="row">'

for i in $FILES
do
    convert -thumbnail 200 $i $DIR/thumb/${i##*/}
    echo -e "\t<div class=\"col-xs-4\">"
    echo -e "\t\t<a href=\"/$i\" class=\"thumbnail\" >"
    echo -e "\t\t  <img src=\"/$DIR/thumb/${i##*/}\" alt=\"thumbnail\" /></a>"
    echo -e "\t</div>"
done

echo '</div>'
