#!/bin/bash

# Set these environment variables to make it work on other systems
[ -n "$JOURNAL_BROWSER" ] || JOURNAL_BROWSER=elinks 
[ -n "$JOURNAL_DIR" ] || JOURNAL_DIR=/home/luke/Dropbox/Apps/Markdown\ Journal/

FILE=$(date +"%Y-%m.%B.markdown")

if [ -f "$JOURNAL_DIR$FILE" ]; then
    pandoc -s "$JOURNAL_DIR$FILE" -o /tmp/$$.html
    $JOURNAL_BROWSER /tmp/$$.html
else
    echo Sorry, no such file
fi
