#!/bin/bash

# Recursive Line Count
# Counts lines in the files with the specified extension; recurses into subdirectories

if [ -z $1 ]; then 
    echo "LCR - Line Count Recursive (by extension)"
    echo "Counts lines in the files in the current directory with the specified extension. Recurses into subdirectories and prints total at the end."
    echo "  Usage: lcr java"
    exit 1
fi

pattern=$1
list=$( find . -type f \( -name "*.$pattern" ! -iname ".*" \) )

if [ -z $list ]; then { echo "No files with that extension were found."; exit 1; }; fi

wc -l $list
