#!/bin/bash

# Set these environment variables to make it work on other systems
[ -n "$JOURNAL_DIR" ] || JOURNAL_DIR=~/Dropbox/Apps/Markdown\ Journal

# Make sure journal folder exists
[ -d "$JOURNAL_DIR" ] || { echo "Journal folder: $JOURNAL_DIR does not exist."; exit 1; }

if [ -z $JOURNAL_SEARCH ]; then
    echo foo $JOURNAL_SEARCH
    # Check if Ag-silver searcher is installed. If not fall back on Grep
    if command -v ag > /dev/null 2>&1; then
        JOURNAL_SEARCH="ag --color-path 0;35"
    else
        JOURNAL_SEARCH="grep"
    fi
fi

if [[ -n "$1" ]]; then
    echo -e "\n\n"
    command -v figlet >/dev/null 2>&1 && { figlet mj-find; }
    echo "Searching for the term '$1' using $JOURNAL_SEARCH."
    echo -e "\n\n"
    $JOURNAL_SEARCH -i "$1" "$JOURNAL_DIR/"*.markdown
else
    echo "No search query. What would you like to search for?"
    exit 1
fi
