#!/bin/bash

# Convert a markdown document to HTML and view it in ELinks
# Uses a new temp file for the output each time

command -v pandoc >/dev/null 2>&1 || { echo "Pandoc is not installed. Please install it and try again"; exit 1; }
command -v pandoc >/dev/null 2>&1 || { echo "Links browser is not installed. Please install it and try again"; exit 1; }

if [ -f "$1" ]; then
    pandoc -s "$1" -o /tmp/$$.html
    links /tmp/$$.html
else
    echo Sorry, no such file
    echo Usage: mkdview filename
fi
