#!/bin/sh

# Run jpegtran recursively on an entire directory

command -v jpegtran >/dev/null 2>&1 || { echo "JPEGTRAN not found. Please install it and try again"; exit 1; }
if test -z $1; then { echo "No directory specified."; echo "Usage: optimize-jpegs [DIRNAME]"; exit 1; }; fi
[ -d $1 ] || { echo "$1 is not a directory"; exit 1; }

TMPDIR=/tmp
# Uncomment if using Cygwin with the windows version of jpegtran
[[ $(uname -s) == "CYGWIN"* ]] && TMPDIR=`cygpath -d /tmp`

jpegs=$(find $1 -iname "*.jpg" | wc -l)
count=1
echo "Found $jpegs files for conversion..."

for f in `find $1 -iname "*.jpg"`;
do
    echo -ne "Optimizing ["
    for in in $(seq 1 $count); do echo -n '#'; done
    for i in $(seq $count $jpegs); do echo -n ' '; done
    echo -ne "] file $count/$jpegs ( $f ) \r"

    count=$((count+1))	
	jpegtran -copy none -progressive -outfile $TMPDIR/$$ "$f"
	mv -f $TMPDIR/$$ $f
done;
echo -ne "\n$count files optimized.\n"
