#!/bin/bash

# Check IP address.

[ -f "$HOME/scripts/colors" ] && source $HOME/scripts/colors

[ -z $1 ] && { echo -e "$Color_Red ERROR:$Color_Off please specify interface (eg. eth0)"; exit 1; }

ifconfig $1 | awk '{ print $2}' | grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}"
